# Generated by Django 4.2.19 on 2025-02-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
