# Generated by Django 4.2.19 on 2025-02-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0002_nickname_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCPartsBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cpu', 'cpu'), ('keyboard', 'keyboard'), ('mouse', 'mouse')], max_length=20)),
                ('image1', models.ImageField(blank=True, upload_to='')),
                ('image2', models.ImageField(blank=True, upload_to='')),
                ('image3', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-dt_created'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image1', models.ImageField(blank=True, upload_to='post_pics')),
                ('image2', models.ImageField(blank=True, upload_to='post_pics')),
                ('image3', models.ImageField(blank=True, upload_to='post_pics')),
                ('content', models.TextField()),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-dt_created'],
            },
        ),
    ]
