# Generated by Django 4.2.19 on 2025-02-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0003_add_post_part_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcpartsboard',
            name='image1',
            field=models.ImageField(blank=True, upload_to='part_pics'),
        ),
        migrations.AlterField(
            model_name='pcpartsboard',
            name='image2',
            field=models.ImageField(blank=True, upload_to='part_pics'),
        ),
        migrations.AlterField(
            model_name='pcpartsboard',
            name='image3',
            field=models.ImageField(blank=True, upload_to='part_pics'),
        ),
    ]
