# Generated by Django 4.2.19 on 2025-02-14 06:31

from django.db import migrations, models
import pc_builder.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pc_builder', '0005_add_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용중인 닉네임입니다.'}, max_length=15, null=True, unique=True, validators=[pc_builder.validators.validate_no_special_characters]),
        ),
    ]
