# Generated by Django 4.2.19 on 2025-03-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField(null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('mall_name', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField(null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('mall_name', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField(null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('mall_name', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('link', models.URLField()),
            ],
        ),
    ]
